# -*- coding: utf-8 -*-
"""PrakAlgo[6]

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8h4wz1Mz0EGOSw-v6cOyDgbMkWWCheZ
"""

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
print("GANJIL -> JARAK TEMPUH")
v0 = float(input("Masukkan vo= "))
t = float(input("Masukkan t ="))
a = float(input("Masukkan a= "))

s = v0 * t + 0.5 * a * t**2

print(f"Jika kecepatan awal= {v0} m/s, percepatan= {a} m/s^2 dan waktu= {t} s, maka Jarak Tempuh adalah {s} meter")

print('@@@@ @@   @ @@@@@  @@@@  @@@@@@ @       @')
print('@  @ @ @  @ @    @ @   @ @      @       @')
print('@@@@ @  @ @ @    @ @   @ @@@@@@ @   @   @')
print('@  @ @   @@ @    @ @@@@  @      @   @   @')
print('@  @ @    @ @@@@@  @   @ @@@@@@ @@@@@@@@@')
from math import*

def luas_kubus(sisi):
    return 6 * sisi**2

def luas_balok(panjang, lebar, tinggi):
    return 2 * (panjang * lebar + panjang * tinggi + lebar * tinggi)

def luas_tabung(jari_jari, tinggi):
    luas_alas = math.pi * jari_jari**2
    luas_permukaan = 2 * math.pi * jari_jari * (jari_jari + tinggi)
    return luas_alas + luas_permukaan

def luas_kerucut(jari_jari, tinggi):
    luas_alas = math.pi * jari_jari**2
    luas_permukaan = math.pi * jari_jari * (jari_jari + math.sqrt(jari_jari**2 + tinggi**2))
    return luas_alas + luas_permukaan

def luas_bola(jari_jari):
    return 4 * math.pi * jari_jari**2

# Meminta pengguna memilih bangun ruang
print("Pilih bangun ruang:")
print("1. Kubus")
print("2. Balok")
print("3. Tabung")
print("4. Kerucut")
print("5. Bola")
print("6. Keluar")
pilihan = int(input("silakan di pilih: "))

if pilihan == 1:
    sisi = float(input("Masukkan panjang sisi kubus: "))
    print("Luas permukaan kubus adalah:", luas_kubus(sisi))
elif pilihan == 2:
    panjang = float(input("Masukkan panjang balok: "))
    lebar = float(input("Masukkan lebar balok: "))
    tinggi = float(input("Masukkan tinggi balok: "))
    print("Luas permukaan balok adalah:", luas_balok(panjang, lebar, tinggi))
elif pilihan == 3:
    jari_jari = float(input("Masukkan jari-jari tabung: "))
    tinggi = float(input("Masukkan tinggi tabung: "))
    print("Luas permukaan tabung adalah:", luas_tabung(jari_jari, tinggi))
elif pilihan == 4:
    jari_jari = float(input("Masukkan jari-jari kerucut: "))
    tinggi = float(input("Masukkan tinggi kerucut: "))
    print("Luas permukaan kerucut adalah:", luas_kerucut(jari_jari, tinggi))
elif pilihan == 5:
    jari_jari = float(input("Masukkan jari-jari bola: "))
    print("Luas permukaan bola adalah:", luas_bola(jari_jari))
elif pilihan == 6:
    print("ok bye")
else:
    print("Pilihan tidak valid.")

